### ISSUE TITLE
Autoneg controller gets confused when Backend Service doesn't exist and example is causing it

### ISSUE THREAD

**Issue by bert-laverman** [GoogleCloudPlatform/gke-autoneg-controller#9] opened 2020-05-04 10:17 UTC
The example in the README uses a Backend Service with a name containing an underscore. However, it is impossible to create a Backend Service with this name.

As a result nothing happens, but even deleting the Service is no longer possible, because the controller keeps getting stuck on the Backend Service name that is rejected.

**Comment by soellman** [comment] 2021-06-08 12:17
Closing this as a dupe of #10 - both are due to the same behavior.

**Closed by soellman** 2021-06-08 12:17 UTC
Labels: bug, duplicate
